### ISSUE TITLE
fail to install lxc containers

### ISSUE THREAD

**Issue by necenzurat** [CZ-NIC/turris-os#85]
````
root@turris:~# lxc-create -t download -n name_of_lxc_container
Setting up the GPG keyring
Downloading the image index
ERROR: Failed to download http://repo.turris.cz/lxc//meta/1.0/index-system
lxc-create: lxccontainer.c: create_run_template: 1201 container creation template for name_of_lxc_container failed
lxc-create: lxc_create.c: main: 274 Error creating container name_of_lxc_container
root@turris:~#
````

Changing the repo to images.linuxcontainers.org works in showing the distributions, but fails and returns an Invalid signature.

Updating the the /usr/share/lxc/templates/lxc-download with the file from https://github.com/lxc/lxc/blob/master/templates/lxc-download.in gives some small progress, but to no avail.

Update:
after alot of hours, it works with the turis repo, but:
1. edit line 44 from /usr/share/lxc/templates/lxc-download
````DOWNLOAD_SHOW_HTTP_WARNING="false"````
2. use this command,
````lxc-create -n debian10 -t download -B best -- -d Debian -r Buster -a armv7l --no-validate````

-d Debian (distribution)
-r Buster (release)
are case sensitive and can be found in the original repo, here: https://repo.turris.cz/lxc//meta/1.0/index-system.2

PS: do this at your own risk. 
[#fml](https://www.urbandictionary.com/define.php?term=FML)

**Comment by BKPepe** [comment]
It's fixed now. Thanks for reporting.

**Comment by omichalek** [comment]
is the fix release please? I still get the same error with Turris 3.11.2

**Comment by BKPepe** [comment]
Hello,

You're responding to issue, which is 4 months ago and yes, we have provided the fix to it. However, it might seem like the same problem, but the issue is different. We have to look at it today and once it would be fixed, I will let you know on the forum, where you have also replied, which won't speed the process of fixing and pushing the fix and it might delay it. Copy-paste responses don't look good and I will need to write something different to you on the forum.

This issue doesn't require to release a new version of Turris OS. 

BTW: I'm locking this conversation here, let's continue on our [forum](https://forum.turris.cz/t/lxc-lxc-create-fails-due-to-missing-ssl/7861/20?u=pepe) as I said.

Best regards,
Pepe
